config:
  credentials:
  - id: upv_im_id
    password_var: IM_PASS
    username_var: IM_USER
  - id: ifca_openstack_id
    password_var: OPENSTACK_PASS
    username_var: OPENSTACK_USER
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
sqa_criteria:
  SvcQC.Dep:
    repos:
      this_repo:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-peach-dragon.sh
        container: svcqc.dep_surly-amaranth-wolf
timeout: 1800
